version: 0.0.{build}-{branch}

branches:
  only:
    - main
    - AppVeyor-Test

init:
  git config --global core.autocrlf input

image:
  Visual Studio 2019
  Ubuntu

platform:
  x86
  x64

configuration:
  Debug
  Release

install:
  mkdir build && cd build

  # Windows
  - cmake .. -G "Visual Studio 16 2019" -A x86 -B x86_Debug -DCMAKE_BUILD_TYPE=Debug
  - cmake .. -G "Visual Studio 16 2019" -A x86 -B x86_Release -DCMAKE_BUILD_TYPE=Release
  - cmake .. -G "Visual Studio 16 2019" -A x64 -B x64_Debug -DCMAKE_BUILD_TYPE=Debug
  - cmake .. -G "Visual Studio 16 2019" -A x64 -B x64_Release -DCMAKE_BUILD_TYPE=Release
  
  # Linux 
  - cmake .. -G "Unix Makefiles" -B linux_Debug -DCMAKE_BUILD_TYPE=Debug
  - cmake .. -G "Unix Makefiles" -B linux_Release -DCMAKE_BUILD_TYPE=Release

build_script:
  # Windows
  - cmake --build x86_Debug --config Debug
  - cmake --build x86_Release --config Release
  - cmake --build x64_Debug --config Debug
  - cmake --build x64_Release --config Release
  
  # Linux
  - cmake --build linux_Debug --config Debug
  - cmake --build linux_Release --config Release

