version: 0.0.{build}-{branch}

# branches to build
branches:
  only:
    - main
    - AppVeyor-Test 

max_jobs: 1


image:
    - Visual Studio 2019
    - Ubuntu

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

matrix:
  exclude:
    - platform: x86
      configuration: Debug

build:
  parallel: true 
