version: 0.0.{build}-{branch}

# branches to build
branches:
  only:
    - main
    - AppVeyor-Test 

max_jobs: 1


image:
    - Visual Studio 2019
    - Ubuntu

platform:
  - x86
  - Any CPU

configuration:
  - Debug
  - Release


matrix:
  fast_finish: true 

  - platform: x86
    configuration: Debug

build:
  parallel: true 
