version: 0.0.{build}-{branch}

branches:
  only:
    - main
    - AppVeyor-Test

init:
  git config --global core.autocrlf input

image:
  - Visual Studio 2019
  - Ubuntu

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

build_script:

    - cmake -B "%APPVEYOR_BUILD_WORKER_IMAGE%" . 
    - cmake --build "%APPVEYOR_BUILD_WORKER_IMAGE%"
