image: 
  - Visual Studio 2017
  - Ubuntu

configuration:
  - Debug
  - Release

platform:
  - x86
  - x64

environment:
  CMAKE_GENERATOR: "Visual Studio 16 2019"

build_script:
  - cmake . -B build/x86/Debug -G "%CMAKE_GENERATOR%" -A Win32 -DCMAKE_BUILD_TYPE=Debug
  - cmake --build build/x86/Debug --config Debug

  - cmake . -B build/x86/Release -G "%CMAKE_GENERATOR%" -A Win32 -DCMAKE_BUILD_TYPE=Release
  - cmake --build build/x86/Release --config Release

  - cmake . -B build/x64/Debug -G "%CMAKE_GENERATOR%" -A x64 -DCMAKE_BUILD_TYPE=Debug
  - cmake --build build/x64/Debug --config Debug

  - cmake . -B build/x64/Release -G "%CMAKE_GENERATOR%" -A x64 -DCMAKE_BUILD_TYPE=Release
  - cmake --build build/x64/Release --config Release

test_script:
  - cd build/x86/Debug
  - ctest --output-on-failure
  - cd ../../x86/Release
  - ctest --output-on-failure
  - cd ../../x64/Debug
  - ctest --output-on-failure
  - cd ../Release
  - ctest --output-on-failure
